server:
  port: 8010
mybatis:
  mapper-locations: classpath:mapping/*.xml
#配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dianpingdb?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: root123
    #使用druid做连接池管理
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    #如果所有的controller都没有命中,则使用默认的静态资源处理
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#使用druid做连接池管理



admin:
  email: 5@qq.com
  encryptPassword: 123456

#es服务
elasticsearch:
  node1: 192.168.76.134:9200